/**
 * Rippling work-location → Home store. Source: current employee roster export.
 */

import { findStaffByEmployeeName, staffDisplayName } from './permissions';
import { canonicalStoreName, storesMatch } from './storeCatalog';

export const EMPLOYEE_ROSTER = [
  {
    id: "6a54e509926ee8d08b8f6bf4",
    fullName: "Kayla Swidrowich",
    firstName: "Kayla",
    lastName: "Swidrowich",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Abbotsford",
  },
  {
    id: "6a8754f7a7719534046057b0",
    fullName: "Sarah Johnston",
    firstName: "Sarah",
    lastName: "Johnston",
    title: "Branch Manager",
    email: "sarah.johnston@canadagold.ca",
    locationName: "Abbotsford",
  },
  {
    id: "6a763cb51dd8cff8da44a713",
    fullName: "Alanna Comber",
    firstName: "Alanna",
    lastName: "Comber",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary North",
  },
  {
    id: "6a1cd0ebdd41c8846d434665",
    fullName: "Andrew Towle",
    firstName: "Andrew",
    lastName: "Towle",
    title: "Bullion, Refining, and Inventory Manager",
    email: "andrew@canadagold.ca",
    locationName: "Calgary North",
  },
  {
    id: "6a29648de840dab341c92204",
    fullName: "Hailey Peabody-ross",
    firstName: "Hailey",
    lastName: "Peabody-Ross",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary North",
  },
  {
    id: "6a1cd0dddd41c8846d434480",
    fullName: "Henrick Yeung",
    firstName: "Ho Kai",
    lastName: "Yeung",
    title: "Precious Metals Analyst",
    email: "henrick@canadagold.ca",
    locationName: "Calgary North",
  },
  {
    id: "6a982334b2c252b4889b6dbf",
    fullName: "Jaz Aiken",
    firstName: "Jasmine",
    lastName: "Aiken",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary North",
  },
  {
    id: "6a1cd0e6bf9c16502da7c4ad",
    fullName: "Jessica Momoh",
    firstName: "Jessica",
    lastName: "Momoh",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary North",
  },
  {
    id: "6a1cd13fdd41c8846d43528a",
    fullName: "Kayleigh Brennan",
    firstName: "Kayleigh",
    lastName: "Brennan",
    title: "Assistant Branch Manager",
    email: "kayleigh@canadagold.ca",
    locationName: "Calgary North",
  },
  {
    id: "6a1cd11add41c8846d434d3a",
    fullName: "Niké Alao",
    firstName: "Moji",
    lastName: "Alao",
    title: "Branch Manager (Calgary NW)/Gemologist",
    email: "nike@canadagold.ca",
    locationName: "Calgary North",
  },
  {
    id: "6a1cd0e8bf9c16502da7c4fc",
    fullName: "Sebastian Powell",
    firstName: "Sebastian",
    lastName: "Powell",
    title: "General Manager - Alberta Branches",
    email: "sebastian.powell@canadagold.ca",
    locationName: "Calgary North",
  },
  {
    id: "6a20859cf446634c360c3181",
    fullName: "Xahra Alexander",
    firstName: "Xahra",
    lastName: "Alexander",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary North",
  },
  {
    id: "6a9ae39eda39ded380cc10ac",
    fullName: "Abby Barton",
    firstName: "Abigail",
    lastName: "Barton",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary SW",
  },
  {
    id: "6a1cd0e8dd41c8846d434616",
    fullName: "Amanda Bongiovanni-Duclos",
    firstName: "Amanda",
    lastName: "Bongiovanni-Duclos",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary SW",
  },
  {
    id: "6a1cd0fcdd41c8846d4348e4",
    fullName: "Ashley Ormson",
    firstName: "Ashley",
    lastName: "Ormson",
    title: "Precious Metals Analyst",
    email: "ashley@canadagold.ca",
    locationName: "Calgary SW",
  },
  {
    id: "6a806d81f4abe49661acef1e",
    fullName: "Craig Schoroth",
    firstName: "Craig",
    lastName: "Schoroth",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary SW",
  },
  {
    id: "6a1cd113dd41c8846d434c4d",
    fullName: "Ian Starkey",
    firstName: "Ian",
    lastName: "Starkey",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary SW",
  },
  {
    id: "6aa8448644c94a249fb0053f",
    fullName: "Igor Lemez",
    firstName: "Igor",
    lastName: "Lemez",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary SW",
  },
  {
    id: "6a1cd136dd41c8846d435148",
    fullName: "Sandeep Rajpurohit",
    firstName: "Sandeep",
    lastName: "Rajpurohit",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary SW",
  },
  {
    id: "6a1cd129dd41c8846d434f6d",
    fullName: "Sara Bernhardt",
    firstName: "Sara",
    lastName: "Bernhardt",
    title: "Precious Metals Analyst",
    email: "sarab@canadagold.ca",
    locationName: "Calgary SW",
  },
  {
    id: "6a1cd102dd41c8846d4349d3",
    fullName: "Angie Pennock",
    firstName: "Andrea (Angie)",
    lastName: "Pennock",
    title: "Assistant Branch Manager",
    email: "angie@canadagold.ca",
    locationName: "Calgary South",
  },
  {
    id: "6a636f847b116081f3234723",
    fullName: "Kateryna Skrypnyk",
    firstName: "Kateryna",
    lastName: "Skrypnyk",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Calgary South",
  },
  {
    id: "6a1cd0f5bf9c16502da7c6d8",
    fullName: "Parker Lileikis",
    firstName: "Parker",
    lastName: "Lileikis",
    title: "Precious Metals Analyst",
    email: "parker.lileikis@canadagold.ca",
    locationName: "Calgary South",
  },
  {
    id: "6a1cd0fdbf9c16502da7c816",
    fullName: "Rajnikant Adesara",
    firstName: "Rajnikant",
    lastName: "Adesara",
    title: "Branch Manager (Calgary) / Gemologist",
    email: "ra@canadagold.ca",
    locationName: "Calgary South",
  },
  {
    id: "69ea23441d120fb5ad27078d",
    fullName: "Alice Zheng",
    firstName: "Xiaotong",
    lastName: "Zheng",
    title: "Operations Manager",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea23271d120fb5ad270362",
    fullName: "Beatrice Roubian",
    firstName: "Beatrice",
    lastName: "Roubian",
    title: "Precious Metals Analyst / Gemologist",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "6a514350083e09123e71948d",
    fullName: "Daniella Shved",
    firstName: "Daniella",
    lastName: "Shved",
    title: "Numismatic Support Associate",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea232c1d120fb5ad27040d",
    fullName: "David Yu",
    firstName: "David",
    lastName: "Yu",
    title: "Shipping Manager",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea232e1d120fb5ad27045d",
    fullName: "Denis Richard",
    firstName: "Denis",
    lastName: "Richard",
    title: "Head Photographer",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea23301d120fb5ad2704b4",
    fullName: "Gerasimos Sofos",
    firstName: "Gerasimos",
    lastName: "Sofos",
    title: "Inventory Assistant",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea23351d120fb5ad27055b",
    fullName: "John Masterson",
    firstName: "John",
    lastName: "Masterson",
    title: "Numsmatist, Retail Associate",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea23371d120fb5ad2705ac",
    fullName: "Lindsay Bolanos",
    firstName: "Lindsay",
    lastName: "Bolanos",
    title: "Director of Operations - Canadian Coin & Currency",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea23391d120fb5ad2705fc",
    fullName: "Maddy Mehi",
    firstName: "Maddy",
    lastName: "Mehi",
    title: "Inventory Associate",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea233b1d120fb5ad27064c",
    fullName: "Mahtab Namavar",
    firstName: "Mahtab",
    lastName: "Nam Avar",
    title: "Customer Care Associate",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea233d1d120fb5ad27069c",
    fullName: "Megan Cole",
    firstName: "Megan",
    lastName: "Cole",
    title: "Ecommerce Associate / Graphic Designer",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea233f1d120fb5ad2706ec",
    fullName: "Michael Pallotta",
    firstName: "Michael",
    lastName: "Pallotta",
    title: "Shipping and Receiving Associate",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea23321d120fb5ad27050b",
    fullName: "Savannah Huang",
    firstName: "Hai Yan",
    lastName: "Huang",
    title: "Inventory Associate",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "69ea23411d120fb5ad27073c",
    fullName: "Valerie Limasi",
    firstName: "Valerie",
    lastName: "Limasi",
    title: "Precious Metals Analyst/ Numismatics Specialist",
    email: "",
    locationName: "Canadian Coin & Currency",
  },
  {
    id: "6a7b7ddef4f2ddaafd2344a2",
    fullName: "Alyssa Barratt",
    firstName: "Alyssa",
    lastName: "Barratt",
    title: "Branch Manager",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad3bde4f3bc617381be5",
    fullName: "Djenny Christina-Myrbel",
    firstName: "Djenny",
    lastName: "Christina-Myrbel",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad3ede4f3bc617381c3d",
    fullName: "Donovan Maric",
    firstName: "Donovan",
    lastName: "Maric",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad4cde4f3bc617381e48",
    fullName: "Gabana Modisa",
    firstName: "Gabana",
    lastName: "Modisa",
    title: "Assistant Branch Manager",
    email: "gabana.modisa@canadagold.ca",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad51de4f3bc617381ef7",
    fullName: "Isra Khan",
    firstName: "Isra",
    lastName: "Khan",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad56de4f3bc617381fa6",
    fullName: "Julie Poirier",
    firstName: "Julie",
    lastName: "Poirier",
    title: "Administrative Assistant",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad59de4f3bc617381ffe",
    fullName: "Kateesha Laurin",
    firstName: "Kateesha",
    lastName: "Laurin",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad5ede4f3bc6173820ae",
    fullName: "Lauren Richardson",
    firstName: "Lauren",
    lastName: "Richardson",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad61de4f3bc617382106",
    fullName: "Lorena Lewis",
    firstName: "Lorena",
    lastName: "Lewis",
    title: "Reception",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad39de4f3bc617381b8d",
    fullName: "Maria Fernandez",
    firstName: "Dignora Maria",
    lastName: "Fernandez",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad6bde4f3bc617382265",
    fullName: "Max Eves",
    firstName: "Max",
    lastName: "Eves",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad6dde4f3bc6173822bd",
    fullName: "Mike Wylie",
    firstName: "Michael",
    lastName: "Wylie",
    title: "General Manager - Jewelry and Refining Services Eastern Canada / General Contractor",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e0eb06197b37762458050c",
    fullName: "Mitch Brule",
    firstName: "Mitchell",
    lastName: "Brule",
    title: "Marketing & Partnerships Coordinator",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad6fde4f3bc617382314",
    fullName: "Nahshon Da Silva",
    firstName: "Nahshon",
    lastName: "Da Silva",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad72de4f3bc61738236c",
    fullName: "Reggie Raphael",
    firstName: "Reginald",
    lastName: "Raphael",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "6a0738d6ee12f53d898d1fac",
    fullName: "Sarah Gaudet",
    firstName: "Sarah",
    lastName: "Gaudet",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad7cde4f3bc6173824cb",
    fullName: "Shawn Foster",
    firstName: "Shawn",
    lastName: "Foster",
    title: "Branch Manager",
    email: "shawn.foster@canadagold.ca",
    locationName: "Carlingwood",
  },
  {
    id: "69e7ad81de4f3bc61738257a",
    fullName: "Tanner Foster",
    firstName: "Tanner",
    lastName: "Foster",
    title: "General Manager - Canada Gold Eastern Canada / Diamond Business Lead Eastern Canada",
    email: "tanner.foster@canadagold.ca",
    locationName: "Carlingwood",
  },
  {
    id: "6a1cd117dd41c8846d434ceb",
    fullName: "Abygael Tackaberry",
    firstName: "Abygael",
    lastName: "Tackaberry",
    title: "Precious Metals Analyst",
    email: "abygael.tackaberry@canadagold.ca",
    locationName: "Edmonton",
  },
  {
    id: "6a4fa0610c644482180b08c2",
    fullName: "Aries Taylor",
    firstName: "Aries",
    lastName: "Taylor",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Edmonton",
  },
  {
    id: "6a6a195d17d413c05ccc62af",
    fullName: "Jhordana Wilson",
    firstName: "Jhordana",
    lastName: "Wilson",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Edmonton",
  },
  {
    id: "6a2c23fd9ec920c6a093a91e",
    fullName: "Joshua Assen",
    firstName: "Joshua",
    lastName: "Assen",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Edmonton",
  },
  {
    id: "6a1cd147dd41c8846d4353ca",
    fullName: "Lexy Ross",
    firstName: "Lexy",
    lastName: "Ross",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Edmonton",
  },
  {
    id: "6a1cd0dfbf9c16502da7c3c0",
    fullName: "Maryna Vince",
    firstName: "Maryna",
    lastName: "Vince",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Edmonton",
  },
  {
    id: "6a1cd141dd41c8846d4352d9",
    fullName: "Michael Mulder",
    firstName: "Michael",
    lastName: "Mulder",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Edmonton",
  },
  {
    id: "6a63a397492d50b0f7297982",
    fullName: "Paige Milroy",
    firstName: "Paige",
    lastName: "Milroy",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Edmonton",
  },
  {
    id: "6a1cd102bf9c16502da7c8b4",
    fullName: "Sara Anselmo",
    firstName: "Sara",
    lastName: "Anselmo",
    title: "District Manager (Edmonton)",
    email: "sara@canadagold.ca",
    locationName: "Edmonton",
  },
  {
    id: "6a1cd0f7dd41c8846d434845",
    fullName: "Emily Schram",
    firstName: "Emily",
    lastName: "Schram",
    title: "Branch Manager (Edmonton)",
    email: "emily@canadagold.ca",
    locationName: "Edmonton West",
  },
  {
    id: "6a296326f88a6f072f0c3602",
    fullName: "Ethan Kainz",
    firstName: "Ethan",
    lastName: "Kainz",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Edmonton West",
  },
  {
    id: "6a1cd115dd41c8846d434c9c",
    fullName: "Kinshuk Sobti",
    firstName: "Kinshuk",
    lastName: "Sobti",
    title: "Gemologist",
    email: "kinshuk.sobti@canadagold.ca",
    locationName: "Edmonton West",
  },
  {
    id: "69e7ad2fde4f3bc617381a2e",
    fullName: "Ashley Moore",
    firstName: "Ashley",
    lastName: "Moore",
    title: "Assistant Branch Manager",
    email: "ashley.moore@canadagold.ca",
    locationName: "Gloucester",
  },
  {
    id: "69e7ad31de4f3bc617381a86",
    fullName: "Brennan Clement",
    firstName: "Brennan",
    lastName: "Clement",
    title: "Senior Precious Metals Analyst",
    email: "",
    locationName: "Gloucester",
  },
  {
    id: "6a22db715e34ff8d22a22d08",
    fullName: "Jessica Young",
    firstName: "Jessica",
    lastName: "Young",
    title: "Branch Manager",
    email: "jessica.young@canadagold.ca",
    locationName: "Gloucester",
  },
  {
    id: "6a207cdfe47b86f816bb627d",
    fullName: "Prince Sapao",
    firstName: "Prince",
    lastName: "Sapao",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Gloucester",
  },
  {
    id: "6a0744625d77f40e03c10827",
    fullName: "Ashleigh Hayes",
    firstName: "Ashleigh",
    lastName: "Hayes",
    title: "Assistant Branch Manager",
    email: "",
    locationName: "Halifax",
  },
  {
    id: "6a0742d419b6ea94ec7cb6c9",
    fullName: "Brian Leader",
    firstName: "Brian",
    lastName: "Leader",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Halifax",
  },
  {
    id: "69e7ad54de4f3bc617381f4f",
    fullName: "Joaquin Marin",
    firstName: "Joaquin",
    lastName: "Marin",
    title: "Branch Manager",
    email: "joaquin.marin@canadagold.ca",
    locationName: "Halifax",
  },
  {
    id: "6a0c635ca84f365cafc61811",
    fullName: "Adriana Jaksic",
    firstName: "Adriana",
    lastName: "Jaksic",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Hamilton",
  },
  {
    id: "69ea1ee8b9bc973c03a72a88",
    fullName: "Brant Fernandez",
    firstName: "Brant Michael",
    lastName: "Fernandez",
    title: "Assistant Branch Manager",
    email: "brant.fernandez@canadagold.ca",
    locationName: "Hamilton",
  },
  {
    id: "69ea1ef0b9bc973c03a72bcc",
    fullName: "Lessmourn Ndlovu",
    firstName: "Lessmourn",
    lastName: "Ndlovu",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Hamilton",
  },
  {
    id: "69ea1ef9b9bc973c03a72d0e",
    fullName: "Samantha Goldsmith",
    firstName: "Samantha",
    lastName: "Goldsmith",
    title: "Branch Manager",
    email: "samantha.goldsmith@canadagold.ca",
    locationName: "Hamilton",
  },
  {
    id: "69e7ad34de4f3bc617381add",
    fullName: "Brock Zwicker",
    firstName: "Brock",
    lastName: "Zwicker",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Laval",
  },
  {
    id: "6a1d9ce7a219eb89014b1dd9",
    fullName: "Marwa Lakehal",
    firstName: "Marwa",
    lastName: "Lakehal",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Laval",
  },
  {
    id: "6a2ffadfbf3f4e700ab0ea7b",
    fullName: "Piyush Churra",
    firstName: "Piyush",
    lastName: "Churra",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Laval",
  },
  {
    id: "6a29656a9ddf51788d269237",
    fullName: "Yarlin Ulloa",
    firstName: "Yarlin",
    lastName: "Ulloa",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Laval",
  },
  {
    id: "6a8c664c2d0bc0699c15e01d",
    fullName: "Yasmine Lakehal",
    firstName: "Yasmine",
    lastName: "Lakehal",
    title: "Assistant Branch Manager",
    email: "yasmine.lakehal@canadagold.ca",
    locationName: "Laval",
  },
  {
    id: "69e7ad86de4f3bc617382629",
    fullName: "Yohance joseph",
    firstName: "Yohance",
    lastName: "Joseph",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Laval",
  },
  {
    id: "6a296a5ae429d121e7e8cdb1",
    fullName: "Yohann Thoby-Timothee",
    firstName: "Yohann",
    lastName: "Thoby-Timothee",
    title: "Branch Manager",
    email: "yohann.thobytimothee@canadagold.ca",
    locationName: "Laval",
  },
  {
    id: "69ea1ee5b9bc973c03a72a38",
    fullName: "Bahir Zahine",
    firstName: "Bahir",
    lastName: "Zahine",
    title: "Assistant Branch Manager",
    email: "bahir.zahine@canadagold.ca",
    locationName: "Mississauga",
  },
  {
    id: "69ea1eeeb9bc973c03a72b7b",
    fullName: "Hassib Zahine",
    firstName: "Hassib Ahmad",
    lastName: "Zahine",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Mississauga",
  },
  {
    id: "6a2960a6df5c9c24b5baa584",
    fullName: "Meagan Singh",
    firstName: "Meagan",
    lastName: "Singh",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Mississauga",
  },
  {
    id: "69ea1ef3b9bc973c03a72c1d",
    fullName: "Muawiz Hashmi",
    firstName: "Muawiz",
    lastName: "Hashmi",
    title: "Branch Manager",
    email: "muawiz.hashmi@canadagold.ca",
    locationName: "Mississauga",
  },
  {
    id: "69ea1ef5b9bc973c03a72c6d",
    fullName: "Neko Ochoa",
    firstName: "Neko",
    lastName: "Ochoa",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Mississauga",
  },
  {
    id: "6a1cd104dd41c8846d434a22",
    fullName: "Sophia Huynh",
    firstName: "Sophia",
    lastName: "Huynh",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Mississauga",
  },
  {
    id: "69ea1f00b9bc973c03a72dff",
    fullName: "Victoria Thomas",
    firstName: "Victoria",
    lastName: "Thomas",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Mississauga",
  },
  {
    id: "69e7ad36de4f3bc617381b35",
    fullName: "Daniel Churchill",
    firstName: "Daniel",
    lastName: "Churchill",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Montreal",
  },
  {
    id: "6a3993defabf5d2e73bd85b1",
    fullName: "Dylan Cox",
    firstName: "Dylan",
    lastName: "Cox",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Montreal",
  },
  {
    id: "69e7ad43de4f3bc617381cec",
    fullName: "Erich Bruening",
    firstName: "Erich",
    lastName: "Bruening",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Montreal",
  },
  {
    id: "69e7ad4ade4f3bc617381df1",
    fullName: "Faith Bosse",
    firstName: "Faith",
    lastName: "Bosse",
    title: "Assistant Branch Manager",
    email: "",
    locationName: "Montreal",
  },
  {
    id: "69e7ad68de4f3bc61738220e",
    fullName: "Marie Therese Boukhaled",
    firstName: "Marie Therese",
    lastName: "Boukhaled",
    title: "Branch Manager",
    email: "marietherese.boukhaled@canadagold.ca",
    locationName: "Montreal",
  },
  {
    id: "69e7ad75de4f3bc6173823c4",
    fullName: "Roman More",
    firstName: "Roman",
    lastName: "More",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Montreal",
  },
  {
    id: "6a22f1257a9f89c8786dce4a",
    fullName: "Ryan Vandewater",
    firstName: "Ryan",
    lastName: "Vandewater",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Montreal",
  },
  {
    id: "6a22f1fe23b6d3d61df63831",
    fullName: "Vincent Bruening",
    firstName: "Vincent",
    lastName: "Bruening",
    title: "Precious Metals Analyst",
    email: "vincent.bruening@canadagold.ca",
    locationName: "Montreal",
  },
  {
    id: "69e7ad2cde4f3bc6173819d7",
    fullName: "Alexandre Daurelle",
    firstName: "Alexandre",
    lastName: "Daurelle",
    title: "Branch Manager - Quebec City (Diamond Certified)",
    email: "",
    locationName: "Quebec",
  },
  {
    id: "69e7ad40de4f3bc617381c95",
    fullName: "Eddie Anuichi",
    firstName: "Edward",
    lastName: "Anuichi",
    title: "General Manager",
    email: "edward.anuichi@canadagold.ca",
    locationName: "Quebec",
  },
  {
    id: "69e7ad5bde4f3bc617382056",
    fullName: "Laura-Lyne Beaudoin",
    firstName: "Laura-Lyne",
    lastName: "Beaudoin",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Quebec",
  },
  {
    id: "6a207c312300e2860ca86c08",
    fullName: "Nailia Latfullina",
    firstName: "Nailia",
    lastName: "Latfullina",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Quebec",
  },
  {
    id: "69e7ad7ade4f3bc617382473",
    fullName: "Samuel Tremblay",
    firstName: "Samuel",
    lastName: "Tremblay",
    title: "Assistant Branch Manager",
    email: "",
    locationName: "Quebec",
  },
  {
    id: "69e7ad47de4f3bc617381d99",
    fullName: "Étienne Dubé",
    firstName: "Étienne",
    lastName: "Dubé",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Quebec",
  },
  {
    id: "69e0eac3197b37762457fc93",
    fullName: "Abigail Mathi-Amorim",
    firstName: "Abigail",
    lastName: "Mathi-Amorim",
    title: "Finance Associate",
    email: "abigail.mathi-amorim@canadagold.ca",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eac6197b37762457fcea",
    fullName: "Alan Chen",
    firstName: "Alan",
    lastName: "Chen",
    title: "Precious Metals Analyst I",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eac8197b37762457fd3d",
    fullName: "Alfredo Cimino",
    firstName: "Alfredo",
    lastName: "Cimino",
    title: "National Director, Numismatics",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "6a07415ace721f5b318a10ea",
    fullName: "Anastasia Mumber",
    firstName: "Anastasia",
    lastName: "Mumber",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eacd197b37762457fdf2",
    fullName: "Andrea Valusek",
    firstName: "Andrea",
    lastName: "Valusek",
    title: "Security",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eb10197b377624580656",
    fullName: "Annie Chow",
    firstName: "Suk Han Annie",
    lastName: "Chow",
    title: "Precious Metals Analyst/ Gemologist",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0ead0197b37762457fe45",
    fullName: "Arielle Rosenberg",
    firstName: "Arielle",
    lastName: "Rosenberg",
    title: "Bookkeeper",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0ead2197b37762457fe97",
    fullName: "Ash Richmond",
    firstName: "Ashley",
    lastName: "Richmond",
    title: "Retail and Customer Experience Manager",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "6aa30c4627833ff53496f095",
    fullName: "Cameron Da Costa",
    firstName: "Raquel",
    lastName: "Da Costa",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0ead5197b37762457fee8",
    fullName: "Candice Au",
    firstName: "Wing Sze",
    lastName: "Au",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0ead7197b37762457ff3b",
    fullName: "Damian Rozen",
    firstName: "Damian",
    lastName: "Rozen",
    title: "General Manager - Bullion B2B and VIP Services",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eadb197b37762457ff8d",
    fullName: "Demetra Sofos",
    firstName: "Demetra",
    lastName: "Sofos",
    title: "Ecommerce Manager",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eae0197b377624580031",
    fullName: "Domenic Moro",
    firstName: "Domenic",
    lastName: "Moro",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eae5197b3776245800d6",
    fullName: "Firas Sassi",
    firstName: "Firas",
    lastName: "Sassi",
    title: "General Manager - Canadian PMX / Project Manager",
    email: "firas.sassi@canadagold.ca",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eae8197b37762458012b",
    fullName: "Heidi Eschbach",
    firstName: "Heidi",
    lastName: "Eschbach",
    title: "Reception",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eaea197b37762458017d",
    fullName: "James Martire",
    firstName: "James",
    lastName: "Martire",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eaed197b3776245801d0",
    fullName: "Jason Lumley",
    firstName: "Jason",
    lastName: "Lumley",
    title: "Storage Services Manager",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eaf2197b377624580275",
    fullName: "Kaon Sterling",
    firstName: "Kaon",
    lastName: "Sterling",
    title: "Facilities and Security Attendant",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eaf4197b3776245802c8",
    fullName: "Kate Marisa",
    firstName: "Katharine",
    lastName: "Marisa",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eafa197b377624580370",
    fullName: "Logan Cooper",
    firstName: "Logan",
    lastName: "Cooper",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eafc197b3776245803c3",
    fullName: "Maria Rodriguez",
    firstName: "Maria",
    lastName: "Rodriguez",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eafe197b377624580416",
    fullName: "Mariya Gorelkina",
    firstName: "Mariya",
    lastName: "Gorelkina",
    title: "Retail and Customer Experience Assistant Manager",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eb04197b3776245804ba",
    fullName: "Matt Conacher",
    firstName: "Matthew",
    lastName: "Conacher",
    title: "Retail Design & Creative Director",
    email: "matt.conacher@canadagold.ca",
    locationName: "Richmond Hill",
  },
  {
    id: "6a43bedc82da8991f8892ab0",
    fullName: "Nico Lafrance",
    firstName: "Nicholas",
    lastName: "Lafrance",
    title: "Customer Experience Coordinator",
    email: "nico@canadagold.ca",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eb08197b37762458055e",
    fullName: "Niko Tsaousidis",
    firstName: "Nikolas",
    lastName: "Tsaousidis",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "6a79f6e6236bb0cc48695955",
    fullName: "Shirin Farahdel",
    firstName: "Shirin",
    lastName: "Farahdel",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eb0e197b377624580603",
    fullName: "Sona Esmailli",
    firstName: "Sona",
    lastName: "Esmailli",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "69e0eb16197b377624580708",
    fullName: "Zev Zak",
    firstName: "Zeev",
    lastName: "Zak",
    title: "Ecommerce Assistant Manager / Bullion Retail Manager",
    email: "",
    locationName: "Richmond Hill",
  },
  {
    id: "6a1cd0e0dd41c8846d4344d5",
    fullName: "Asher Haque",
    firstName: "Asher",
    lastName: "Haque",
    title: "Branch Manager",
    email: "asher@canadagold.ca",
    locationName: "Surrey",
  },
  {
    id: "6a1cd0e2dd41c8846d434524",
    fullName: "Benjamin Sanju",
    firstName: "Benjamin",
    lastName: "Sanju",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Surrey",
  },
  {
    id: "6a281298aa953ea872c1d872",
    fullName: "Jin Vincent",
    firstName: "Janikwa",
    lastName: "Vincent",
    title: "Precious Metals Analyst - Part Time",
    email: "",
    locationName: "Surrey",
  },
  {
    id: "6a1cd10fdd41c8846d434baf",
    fullName: "Katie Lai",
    firstName: "Katie",
    lastName: "Lai",
    title: "Gemologist",
    email: "",
    locationName: "Surrey",
  },
  {
    id: "6a1cd100dd41c8846d434984",
    fullName: "Kelvin Prakasan",
    firstName: "Kelvin",
    lastName: "Prakasan",
    title: "Precious Metals Analyst",
    email: "kelvin@canadagold.ca",
    locationName: "Surrey",
  },
  {
    id: "6a1cd0f3bf9c16502da7c689",
    fullName: "Melina Bourne",
    firstName: "Melina",
    lastName: "Bourne",
    title: "Precious Metals Analyst",
    email: "melina@canadagold.ca",
    locationName: "Surrey",
  },
  {
    id: "6a07252abb488731188a403e",
    fullName: "Sakif Choudhury",
    firstName: "SAKIF",
    lastName: "CHOUDHURY",
    title: "Precious Metals Analyst",
    email: "sakif@canadagold.ca",
    locationName: "Surrey",
  },
  {
    id: "69ea1eeab9bc973c03a72ad9",
    fullName: "Cadence Copeland",
    firstName: "Cadence",
    lastName: "Copeland-Kraut",
    title: "Precious Metals Analyst (Diamond Certified)",
    email: "cadence.copeland@canadagold.ca",
    locationName: "Toronto",
  },
  {
    id: "69ea1eecb9bc973c03a72b2a",
    fullName: "Fintan Carolan",
    firstName: "Fintan",
    lastName: "Carolan",
    title: "Assistant Branch Manager",
    email: "fintan.carolan@canadagold.ca",
    locationName: "Toronto",
  },
  {
    id: "6a3ae9aff3e996cf6e5f97e7",
    fullName: "Jack Stamcos",
    firstName: "Jack",
    lastName: "Stamcos",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Toronto",
  },
  {
    id: "69ea1ef7b9bc973c03a72cbe",
    fullName: "Oliver Berry",
    firstName: "Oliver",
    lastName: "Berry",
    title: "General Manager - Canada Gold GTA",
    email: "oliver.berry@canadagold.ca",
    locationName: "Toronto",
  },
  {
    id: "69ea1efbb9bc973c03a72d5e",
    fullName: "Simon Sheung",
    firstName: "Simon",
    lastName: "Sheung",
    title: "Branch Manager",
    email: "simon.sheung@canadagold.ca",
    locationName: "Toronto",
  },
  {
    id: "69ea1efeb9bc973c03a72dae",
    fullName: "Troy Francis",
    firstName: "Troy",
    lastName: "Francis",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Toronto",
  },
  {
    id: "6a1cd10bdd41c8846d434b0f",
    fullName: "Ali Fletcher",
    firstName: "Ali",
    lastName: "Fletcher",
    title: "Director, Retail Operations",
    email: "ali.fletcher@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd108dd41c8846d434ac0",
    fullName: "Amandeep kaur",
    firstName: "Amandeep",
    lastName: "kaur",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd106bf9c16502da7c954",
    fullName: "Blair Westerberg",
    firstName: "Blair",
    lastName: "Westerberg",
    title: "Precious Metals Analyst",
    email: "blair@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd12bdd41c8846d434fbc",
    fullName: "Catlin Aho",
    firstName: "Catlin",
    lastName: "Aho",
    title: "Refining and Administration Manager",
    email: "catlin@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd125dd41c8846d434ecd",
    fullName: "Christina Wong",
    firstName: "Christina",
    lastName: "Wong",
    title: "Precious Metals Analyst",
    email: "christina@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd106dd41c8846d434a71",
    fullName: "Enzo Busto",
    firstName: "Enzo",
    lastName: "Busto",
    title: "Finance Director",
    email: "enzo.busto@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1da2d9a3946f1c1e195c22",
    fullName: "EsaBella Strickland",
    firstName: "ESABELLA",
    lastName: "STRICKLAND",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd12ddd41c8846d43500b",
    fullName: "Evan Eye",
    firstName: "Evan",
    lastName: "Eye",
    title: "product photographer / Precious Metals Analyst",
    email: "evan@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd134dd41c8846d4350f9",
    fullName: "Jamie Browne",
    firstName: "Jamie",
    lastName: "Browne",
    title: "Precious Metals Analyst",
    email: "jamie@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd0eddd41c8846d4346b4",
    fullName: "Jordan Fassina",
    firstName: "Jordan",
    lastName: "Fassina",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd0e3bf9c16502da7c45e",
    fullName: "Karla Burdge",
    firstName: "Karla",
    lastName: "Burdge",
    title: "Gemologist / Diamond Inventory Manager",
    email: "karla@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd0f3dd41c8846d4347a5",
    fullName: "Kourosh Mirabian",
    firstName: "Kourosh",
    lastName: "Mirabian",
    title: "High Jewellery Specialist",
    email: "kourosh@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd0f0bf9c16502da7c63a",
    fullName: "Martin Weintritt",
    firstName: "Martin",
    lastName: "Weintritt",
    title: "Precious Metals Analyst",
    email: "martin.weintritt@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd111dd41c8846d434bfe",
    fullName: "May Pantaleon",
    firstName: "May",
    lastName: "Pantaleon",
    title: "Precious Metals Analyst",
    email: "may.pantaleon@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd100bf9c16502da7c865",
    fullName: "Shannon Stewart",
    firstName: "Shannon",
    lastName: "Stewart",
    title: "Senior Precious Metals Analyst",
    email: "shannon@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a1cd0eabf9c16502da7c54b",
    fullName: "Vicky Athanassakis",
    firstName: "Vicky",
    lastName: "Athanassakis",
    title: "Retail and Customer Experience Manager",
    email: "vicky@canadagold.ca",
    locationName: "Vancouver",
  },
  {
    id: "6a4e88746638a9d53667aa55",
    fullName: "Abdulsamad Olawale",
    firstName: "Abdulsamad",
    lastName: "Olawale",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Winnipeg",
  },
  {
    id: "6a048e8d8fe4fe28e77635eb",
    fullName: "Brayden Barroso",
    firstName: "Brayden",
    lastName: "Barroso",
    title: "Branch Manager",
    email: "",
    locationName: "Winnipeg",
  },
  {
    id: "6a2ff719438e57f2d406b1a1",
    fullName: "Ikechi Umeh",
    firstName: "Ikechi",
    lastName: "Umeh",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Winnipeg",
  },
  {
    id: "6a398976241e0b2e2de78548",
    fullName: "Robert Tober",
    firstName: "Robert",
    lastName: "Tober",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Winnipeg",
  },
  {
    id: "6a9ae5febd0493586e7afe6d",
    fullName: "Sana Ueno",
    firstName: "Sana",
    lastName: "Ueno",
    title: "Precious Metals Analyst",
    email: "",
    locationName: "Winnipeg",
  },
];

export function findEmployeeRosterPerson(personOrName) {
  if (personOrName == null) return null;
  if (typeof personOrName === 'string') {
    return findStaffByEmployeeName(EMPLOYEE_ROSTER, personOrName);
  }
  return (
    findStaffByEmployeeName(EMPLOYEE_ROSTER, staffDisplayName(personOrName)) ||
    findStaffByEmployeeName(EMPLOYEE_ROSTER, personOrName.fullName || personOrName.firstName) ||
    (personOrName.email
      ? EMPLOYEE_ROSTER.find(
          (row) =>
            row.email &&
            row.email.localeCompare(personOrName.email, undefined, { sensitivity: 'base' }) === 0,
        )
      : null)
  );
}

function rosterPersonRow(row) {
  return {
    id: `roster-${row.id || row.fullName}`,
    ripplingId: row.id || '',
    aureusUserId: '',
    aureusLogin: '',
    firstName: row.firstName || '',
    lastName: row.lastName || '',
    fullName: row.fullName || '',
    email: row.email || '',
    phone: '',
    role: row.title || '',
    employeeType: '',
    locationId: '',
    locationName: row.locationName || '',
    isActive: true,
    photoUrl: '',
    profileId: '',
    avatarUrl: '',
    appRole: '',
    isSystemAdmin: false,
    hasSignedIn: false,
    profileActive: true,
    posRole: row.title || '',
    rosterSource: 'hr',
  };
}

export function applyEmployeeRosterLocation(person) {
  const hit = findEmployeeRosterPerson(person);
  if (!hit) return person;
  const locationName = canonicalStoreName(hit.locationName) || hit.locationName;
  if (!locationName) return person;
  return { ...person, locationName };
}

/** Overlay Excel store assignments and add roster-only retail staff. */
export function mergeStaffWithEmployeeRoster(staff) {
  const rows = (Array.isArray(staff) ? staff : []).map(applyEmployeeRosterLocation);
  const used = new Set();
  for (const row of rows) {
    const hit = findEmployeeRosterPerson(row);
    if (hit?.id) used.add(hit.id);
    if (hit?.fullName) used.add(hit.fullName.toLowerCase());
  }
  for (const row of EMPLOYEE_ROSTER) {
    if (used.has(row.id) || used.has(row.fullName.toLowerCase())) continue;
    rows.push(rosterPersonRow(row));
  }
  rows.sort((a, b) =>
    staffDisplayName(a).localeCompare(staffDisplayName(b), undefined, { sensitivity: 'base' }),
  );
  return rows;
}

export function rosterEmployeesForStore(storeName) {
  const name = canonicalStoreName(storeName);
  if (!name) return [];
  return EMPLOYEE_ROSTER.filter((row) => storesMatch(row.locationName, name)).map(rosterPersonRow);
}
